### ISSUE TITLE
Get Lyrics call from script

### ISSUE THREAD

**Issue by aidanmischke** [luminescence-software/scripts#2]
Hi there,

Great software!
How would I go about calling the Get Lyrics feature within a script?

Context
I have a Title of:
Feel So Close - Calvin Harris
Which I will cut up to pass to the Lyrics search call.
(Lyrics search is uses tags ARTIST and TITLE which have to be exact)

Thanks!

**Comment by CyberSinh** [comment]
It's already possible:

```cs
using Metatogger.Business;
using Metatogger.Data;

foreach (var file in files)
{
  string artist = file.GetFirstValue(TagName.Artist);
  string title = file.GetFirstValue(TagName.Title);
  if (artist != null && title != null)
  {
    string lyrics = await LyricsWikiaServices.GetSongAsync(artist, title);
    if (lyrics != null)
      file.SetTag(TagName.Lyrics, lyrics);   
  }
}
```

**Comment by aidanmischke** [comment]
Thanks!

As Wikia Lyrics couldn't find lyrics for certain songs is it possible to access a different lyrics service from a Metatogger script?

**Comment by CyberSinh** [comment]
Metatogger doesn't support natively another lyrics provider.
But you can call any webservice on internet with C# script...

**Comment by CyberSinh** [comment]
Lyrics Wikia is not supported anymore in Metatogger.
