### ISSUE TITLE
quick , easy question hopefully

### ISSUE THREAD

**Issue by MKrehelJr** [luminescence-software/scripts#6]
I'm using metatogger and I've transferred about 11 thousand flac files and I need to copy the information from a tag in the file called "TTTL" to the "Title" tag in the same file. It looks like it should be easy with the scripting, but I don't seem to be able to figure it out. I can't find any documentation of available objects and syntax.

If you could help me out it would be greatly appreciated!

Thank you in advance.

**Comment by CyberSinh** [comment]
Use the "Edit tags" tools and enter `|titl|` in the Title tag filed.
